language: java

jdk:
  - openjdk-ea
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

notifications:
  email: false

env:
  global:
    - secure: "Kj1H42vM5f0cbNHF4DBlo+oXM5f+3mGRcwkAKkpQiaO0ZtvQlOyJLBz1WA04CevVSk0qTOyPfH1sjza9wz7mZS0rwsv9fF9Vqf5CYZQSqt3VsfQVN6eS9ZQcO3MF33q1bDkZ4uIFjCY9er0gm0OKT61tmAmdbr7CsAMc80NidI9XCTLNoN+1qYXTcOIzDcyFD+ZNT3DvCw3CQRLWm6tnKD/OKflWM+q4Ck4rPt9wLcrpicA3cxUDRj25m45BV6rBlMDWCXvSeQYBbXoqeZ2WxICtDYeMVVCfpsTTsJOMK1gWRAY1ca6Ri2u81Rc3Nm5GYxsRzBrhWZZec4uu7bL2c/Km8gvbjaU7lnhZzWtFRSdGThEuyYf2PWIhnuDbWTSljMY0PFFRu/WekbfuoIVXcjCZVGXVN+CTemWWEr5S/mcnRZe6/k1NTHeQKfENKx3Xlein6C3hm+u3/xkknDXDmjiy9GxBwNzbInqls1RmqZYt23WMYkpA71MB6wgoDbMLHtt2CPuhOyXk3TxP2BoR2uQPX/hanVAbLmjQssWtcrWUi4aZc1gmLkRZ6NaQvTNK2MepOuJa/5fCRUIYOhmulCL8fii6wA/qJNlJRhkfpeS4Aul5sw38fVyBuTxeEoEZHOARUat5nDEq338LMH995sCKTo4xgmX1dv42euCjhdM="

addons:
  sonarcloud:
    organization: "fartherp"
    token:
      secure: "G0+FrHepF4yGOLia2D2tvMi6mhAaHSX1WgxLiEmuDQxl4eQdobgfinxl2qaIlgZdNVU46Ry9ELIFipEQMQ+kpkpLhg5zfbY0mQhucAwJdmJQ0QC/KOcEiohQEdFK4uFrrET8UrDeQ9U599T3V6C8ipisDgknY4lpZ/qlgbOGKf1fQ/hBLUdSB1dsx5yXzBc+noHgz/tbnyeC6uwe39aBnmk9mynYEPinxdq7MAHoSUrbxQJFHLa9b2LbKTXfGX0vQlkxgFP47mOuUUWl/spPFBDaYaa9UGi3xdJOq4qL/CeHxCY4zxmsOpzTOcTt1zoRs6JwuiIk/YIgdKMIGR0jOWsOOINCrPFlnbhIkckxL/stH2Pc/boYLQrbyyEc3PrQBOJrSY5m0efbdG45ny61CC0GGv8/Siidb4t4HUCnN5nxBjCwBuvqWqbZYxU0NW8rWsG9Ytz0/rAQjTJgDxfxB6euim9K8NVnIove8UI0QVoLzqs3AY4LM6bnRcSKLKyzcn038WG+ziJLdW0YDpkyZTZaf3nktYZ9oJy7//2XGWxQZE4NUtliBAv5YqKqLFdnUFeMuL2ycosmny5eyLHAkzR3a02+OEKEEc6PXbgDCRUnEWRwG/NLiqmUQjTPoqKsfwTphdRCxTgrPAf+HLOHZ+psKnQqWQUiWDsB8GzC04w="